name: Convert DEV Posts to Jekyll Markdown
on:
  schedule:
    # At midnight twice a week on Monday and Thursday
    - cron:  '*/5 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  dev-to-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: dev-to-md
        uses: coderganesh/Dev.to-md@master
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_API_KEY: "${{ secrets.DEV_API_KEY }}"
      NUM_OF_POSTS: "${{ secrets.NUM_OF_POSTS }}"